name: Lighthouse Performance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          mkdir -p .lighthouseci
          cat > .lighthouseci/lighthouserc.json << 'EOF'
          {
            "ci": {
              "collect": {
                "staticDistDir": "./",
                "url": ["http://localhost:8080/index.html", "http://localhost:8080/technical-details.html"]
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["warn", {"minScore": 0.7}],
                  "categories:accessibility": ["warn", {"minScore": 0.8}],
                  "categories:best-practices": ["warn", {"minScore": 0.8}],
                  "categories:seo": ["warn", {"minScore": 0.7}]
                }
              }
            }
          }
          EOF
          
          # Start HTTP server on port 8080 (no sudo required)
          python3 -m http.server 8080 &
          SERVER_PID=$!
          
          # Wait for server to start
          echo "Waiting for server to start..."
          sleep 10
          
          # Test server availability
          curl -f http://localhost:8080/index.html > /dev/null || {
            echo "Server failed to start or serve content"
            kill $SERVER_PID 2>/dev/null || true
            exit 1
          }
          
          # Run Lighthouse CI
          lhci autorun || {
            echo "Lighthouse CI failed, but continuing..."
            kill $SERVER_PID 2>/dev/null || true
            exit 0
          }
          
          # Clean up server
          kill $SERVER_PID 2>/dev/null || true

      - name: Upload Lighthouse Results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/