name: Lighthouse Performance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          mkdir -p .lighthouseci
          echo '{
            "ci": {
              "collect": {
                "staticDistDir": "./",
                "url": ["http://localhost/index.html", "http://localhost/technical-details.html"]
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["error", {"minScore": 0.8}],
                  "categories:accessibility": ["error", {"minScore": 0.9}],
                  "categories:best-practices": ["error", {"minScore": 0.9}],
                  "categories:seo": ["error", {"minScore": 0.8}]
                }
              }
            }
          }' > .lighthouseci/lighthouserc.json
          
          # Start a simple HTTP server
          python3 -m http.server 80 &
          sleep 5
          
          # Run Lighthouse CI
          lhci autorun

      - name: Upload Lighthouse Results
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: .lighthouseci/